version: "2"
linters:
  enabled:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - exhaustive
    - errorlint
    - nilerr
    - bodyclose
    - gosec
    - modernize
  settings:
    exhaustive:
      default-signifies-exhaustive: true
  exclusions:
    generated: lax
    paths:
      - ^\.direnv/
formatters:
  enable:
    - gofmt